routes/web.php
<?php

use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RolesController;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Route::get('/dashboard', function () {
    return view('admin.dashboard');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
    //All the routes that belongs to the group goes here
    Route::get('permission', [PermissionController::class, 'index'])->name('permission.index');
    Route::resource('roles', RolesController::class);
});
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer-component.blade.php
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-md-12 col-sm-12 text-center">
                Selamat Datang di scaffholding laravel Sash by Syahrul Setiawan
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/left-sidebar-component.blade.php
<div class="sticky">
    <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
    <div class="app-sidebar">
        <div class="side-header">
            <a class="header-brand1" href="{{ url('/') }}">
                <img src="../assets/images/brand/logo.png" class="header-brand-img desktop-logo" alt="logo">
                <img src="../assets/images/brand/logo-1.png" class="header-brand-img toggle-logo" alt="logo">
                <img src="../assets/images/brand/logo-2.png" class="header-brand-img light-logo" alt="logo">
                <img src="../assets/images/brand/logo-3.png" class="header-brand-img light-logo1" alt="logo">
            </a>
            <!-- LOGO -->
        </div>
        <div class="main-sidemenu">
            <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191"
                    width="24" height="24" viewBox="0 0 24 24">
                    <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" /></svg>
            </div>
            <ul class="side-menu">
                <li class="sub-category">
                    <h3>Main</h3>
                </li>
                <x-basic-sidebar-component link="{{ url('/') }}" activate="">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-home"></i></x-slot>
                    <x-slot name="text">Dashboard</x-slot>
                </x-basic-sidebar-component>
                <li class="sub-category">
                    <h3>User & Roles management</h3>
                </li>
                <x-basic-sidebar-component link="{{ url('/') }}" activate="">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-home"></i></x-slot>
                    <x-slot name="text">User Management</x-slot>
                </x-basic-sidebar-component>
                <x-basic-sidebar-component link="{{ route('roles.index') }}" activate="">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-user-check"></i></x-slot>
                    <x-slot name="text">Roles</x-slot>
                </x-basic-sidebar-component>
                <x-basic-sidebar-component link="{{ route('permission.index') }}" activate="">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-unlock"></i></x-slot>
                    <x-slot name="text">Permission</x-slot>
                </x-basic-sidebar-component>
                
                

                {{-- contoh --}}
                <li class="sub-category">
                    <h3>Sub Category Menu</h3>
                </li>
                <x-basic-sidebar-component link="{{ url('/') }}" activate="">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-home"></i></x-slot>
                    <x-slot name="text">Basic SideBar</x-slot>
                </x-basic-sidebar-component>
                
                <x-multi-sidebar-component title="Multi Sidebar">
                    <x-slot name="icon"><i class="side-menu__icon fe fe-map-pin"></i></x-slot>
                    <x-sub-multi-sidebar-component link="dadasd" title="Submenu"></x-sub-multi-sidebar-component>
                    <x-sub-multi-sidebar-component link="dasdhjasd" title="Submenu"></x-sub-multi-sidebar-component>
                    <x-sub-multi-sidebar-component link="dadasd" title="Submenu"></x-sub-multi-sidebar-component>
                </x-multi-sidebar-component>
                {{-- contoh --}}
            </ul>
            <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24"
                    height="24" viewBox="0 0 24 24">
                    <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                </svg></div>
        </div>
    </div>
    <!--/APP-SIDEBAR-->
</div>